version: 1.64.8

linters:
  enable:
    - errcheck
    - gosec
    - staticcheck
    - revive
    - gocritic
    - wrapcheck
linters-settings:
  gosec:
    excludes:
      - G204  # subprocess via variable is intentional for session-manager-plugin
